### PR TITLE
Security fixes

### PR DESCRIPTION
**Pull request by sshedi**

### CODE REVIEW

**Comment by sshedi** [comment]
cc: @suezzelur @tapakund @satya-rajesh

**Comment by satya-rajesh** [comment]
could you also please update log4j in vmidentity/rest/idm/samples/pom.xml.

There are log4j vulnerabilities reported on this file by github:

[SQL Injection in Log4j 1.2.x ]Critical
log4j:log4j (Maven) · vmidentity/rest/idm/samples/pom.xml
Users should upgrade to Log4j 2

[Deserialization of Untrusted Data in Log4j 1.x ]High
log4j:log4j (Maven) · vmidentity/rest/idm/samples/pom.xml ·
Users should upgrade to Log4j 2

**Comment by sshedi** [comment]
I think this file is okay.

It is using `vmidentity/rest/idm/samples/pom.xml:99:      <version>${log4j.12.api.version}</version>`
this is defined in `vmidentity/pom.xml:334:    <log4j.12.api.version>2.17.2</log4j.12.api.version>`

So we are good here.

**Comment by satya-rajesh** [comment]
changes look to me.
a small question, did we build with this change ?

**Review by tapakund — APPROVED** [review]
Changes looks good.

**Comment by sshedi** [comment]
Built lightwave on Photon-3.0 & build is fine.

**Comment by satya-rajesh** [comment]
> Built lightwave on Photon-3.0 & build is fine.

Looks good to me, thanks for the update.

**Pull request merged**
